/* ============================================================
   movies.js — Leveny
   SINGLE SOURCE OF TRUTH for all movies.
   To add a new movie: just add one entry to this array.
   Everything else (desktop search, mobile search on every
   movie page, discover pages) updates automatically.
   
   discover: 1=blue, 2=yellow, 3=green, 4=red, 5=dark, 6=orange, 7=purple
============================================================ */

const LEVENY_MOVIES = [
    { title: "Avatar: The Way of Water",        href: "../movies/avatar_way_of_water_movie.html",         genre: "scifi",     poster: "images/posters/avatar_water.jpg",    discover: 1,    background: "images/backgrounds/awow.jpg"},
    { title: "The Meg",                          href: "../movies/the_meg_movie.html",                     genre: "action",    poster: "images/posters/themeg.jpg",           discover: 1,    background: "images/backgrounds/themeg.jpg"},
    { title: "The Little Mermaid",               href: "../movies/the_littlemermaid_movie.html",           genre: "family",    poster: "images/posters/littlemermaid.jpg",    discover: 1,    background: "images/backgrounds/littlemermaid.jpg"},
    { title: "Finding Dory",                     href: "../movies/finding_dory_movie.html",                genre: "animation", poster: "images/posters/findingdory.jpg",      discover: 1,    background: "images/backgrounds/fd.jpg"},
    { title: "Percy Jackson: The Lightening Thief",  href: "../movies/percy_jackson_movie.html",               genre: "fantasy",   poster: "images/posters/percyjackson.jpg",     discover: 1,    background: "images/backgrounds/percyjackson.jpg"},
    { title: "Sonic: The Hedgehog",              href: "../movies/sonic_movie.html",                       genre: "scifi",     poster: "images/posters/sonic.jpg",            discover: 1,    background: "images/backgrounds/sonic.jpg"},
    { title: "Lilo and Stitch",                  href: "../movies/lilo_stitch_movie.html",                 genre: "animation", poster: "images/posters/lilo.jpg",             discover: 1,    background: "images/backgrounds/llss.jpg"},
    { title: "Tron: Legacy",                     href: "../movies/tron_movie.html",                        genre: "scifi",     poster: "images/posters/tron.jpg",             discover: 1,    background: "images/backgrounds/tr.jpg"},
    { title: "Jurassic World: Dominion",         href: "../movies/jurassic_park_dominion_movie.html",      genre: "action",    poster: "images/posters/jurassic_dominion.jpg", discover: 2,    background: "images/backgrounds/jurassic_dominion.jpg"},
    { title: "The Beekeeper",                    href: "../movies/the_beekeeper_movie.html",               genre: "action",    poster: "images/posters/bee.jpg",              discover: 2,    background: "images/backgrounds/bee.jpg"},
    { title: "Transformers: Bumblebee",          href: "../movies/bumblebee_movie.html",                   genre: "scifi",     poster: "images/posters/bumble.jpg",           discover: 2,    background: "images/backgrounds/bb.jpg"},
    { title: "Jumanji: Welcome to the Jungle",   href: "../movies/jumanji_movie.html",                     genre: "action",    poster: "images/posters/jumanji.jpg",          discover: 2,    background: "images/backgrounds/jm.jpg"},
    { title: "Knives Out",                       href: "../movies/knives_out_movie.html",                  genre: "thriller",  poster: "images/posters/knives.jpg",           discover: 2,    background: "images/backgrounds/ko.jpg"},
    { title: "Minions: Rise of Gru",             href: "../movies/minions_rise_of_gru_movie.html",         genre: "animation", poster: "images/posters/minions.jpg",          discover: 2,    background: "images/backgrounds/rog.jpg"},
    { title: "Uncharted",                        href: "../movies/uncharted_movie.html",                   genre: "action",    poster: "images/posters/uncharted.jpg",        discover: 2,    background: "images/backgrounds/un.jpg"},
    { title: "Wolverine",                           href: "../movies/wolverine_movie.html",                   genre: "superhero", poster: "images/posters/wolver.jpg",        discover: 2,    background: "images/backgrounds/wol.jpg"},
    { title: "Green Lantern",                    href: "../movies/green_lantern_movie.html",               genre: "superhero", poster: "images/posters/gl.jpg",               discover: 3,    background: "images/backgrounds/ggl.jpg"},
    { title: "The Jungle Book",                      href: "../movies/jungle_book_movie.html",                 genre: "family",    poster: "images/posters/jb.jpg",               discover: 3,    background: "images/backgrounds/jb.jpg"},
    { title: "The Matrix",                       href: "../movies/the_matrix_movie.html",                  genre: "scifi",     poster: "images/posters/ma.jpg",               discover: 3,    background: "images/backgrounds/ma.jpg"},
    { title: "Oz: The Great and Powerful",       href: "../movies/the_wizard_of_oz_movie.html",            genre: "fantasy",   poster: "images/posters/oz.jpg",               discover: 3,    background: "images/backgrounds/wo.jpg"},
    { title: "Shrek 2",                          href: "../movies/shrek_2_movie.html",                     genre: "animation", poster: "images/posters/sh.jpg",               discover: 3,    background: "images/backgrounds/sh.jpg"},
    { title: "Raya and the Last Dragon",         href: "../movies/raya_and_the_last_dragon_movie.html",    genre: "animation", poster: "images/posters/ry.jpg",               discover: 3,    background: "images/backgrounds/ra.jpg"},
    { title: "Wicked",                           href: "../movies/wicked_movie.html",                      genre: "musical",   poster: "images/posters/wi.jpg",               discover: 3,    background: "images/backgrounds/wi.jpg"},
    { title: "Deadpool",                         href: "../movies/deadpool_movie.html",                    genre: "superhero", poster: "images/posters/deadpool.jpg",         discover: 4,    background: "images/backgrounds/dp.jpg"},   
    { title: "Descendants: Rise of Red",                 href: "../movies/descendants_rise_of_red_movie.html",     genre: "musical",   poster: "images/posters/dr.jpg",              discover: 4,    background: "images/backgrounds/rise_of_red_backg.jpg"},
    { title: "It: Chapter One",                  href: "../movies/it_movie.html",                          genre: "horror",    poster: "images/posters/it.jpg",               discover: 4,    background: "images/backgrounds/it_backg.jpg"},
    { title: "Superman: Legacy",                 href: "../movies/superman_legacy_movie.html",              genre: "superhero", poster: "images/posters/su.jpg",               discover: 4,    background: "images/backgrounds/superman_backg.jpg"},
    { title: "Mulan",                            href: "../movies/mulan_movie.html",                       genre: "fantasy",   poster: "images/posters/mu.jpg",               discover: 4,    background: "images/backgrounds/mulan_backg.jpg"},
    { title: "Turning Red",                      href: "../movies/turning_red_movie.html",                 genre: "animation", poster: "images/posters/tr.jpg",               discover: 4,    background: "images/backgrounds/turning_red_backg.jpg"},
    { title: "Spider-Man: No Way Home",          href: "../movies/spider_man_no_way_home_movie.html",      genre: "superhero", poster: "images/posters/sp.jpg",               discover: 4,    background: "images/backgrounds/spiderman_no_way_home_backg.jpg"},
    { title: "Red One",                          href: "../movies/red_one_movie.html",                     genre: "family",    poster: "images/posters/ro.jpg",               discover: 4,    background: "images/backgrounds/red_one_backg.jpg"},
    { title: "Batman: The Dark Knight",          href: "../movies/batman_the_dark_knigt_movie.html",       genre: "superhero", poster: "images/posters/batman_dark.jpg",      discover: 5,    background: "images/backgrounds/batman.jpg"},
    { title: "Cruella",                          href: "../movies/cruella_movie.html",                     genre: "family",    poster: "images/posters/cr.jpg",               discover: 5,    background: "images/backgrounds/cruella_backg.jpg"},
    { title: "Scream",                           href: "../movies/scream_movie.html",                      genre: "horror",    poster: "images/posters/sc.jpg",               discover:5,    background:"images/backgrounds/scream_backg.jpg"},
    { title: "The Nun",                          href: "../movies/the_nun_movie.html",                     genre: "horror",    poster: "images/posters/tn.jpg",              discover:5,    background:"images/backgrounds/the_nun_backg.jpg"},
    { title: "A Quiet Place",                    href: "../movies/a_quiet_place_movie.html",               genre: "thriller",  poster: "images/posters/qp.jpg",               discover:5,    background:"images/backgrounds/a_quiet_place_backg.jpg"},
    { title: "Twilight",                         href: "../movies/twilight_movie.html",                    genre: "fantasy",   poster: "images/posters/tw.jpg",              discover:5,    background:"images/backgrounds/twilight_backg.jpg"},
    { title: "Maleficent: Mistress of Evil",     href: "../movies/maleficent_movie.html",                  genre: "fantasy",   poster: "images/posters/ml.jpg",               discover: 5   ,    background: "images/backgrounds/maleficent_backg.jpg"},
    { title: "Knives Out: Wake Up Dead Man",     href: "../movies/knives_out_wake_up_dead_man_movie.html", genre: "thriller",  poster: "images/posters/kowu.jpg",             discover: 5   ,    background: "images/backgrounds/knives_out_wake_up_dead_man_backg.jpg"},
    { title: "The Lion King",                    href: "../movies/lion_king_movie.html",                   genre: "family",    poster: "images/posters/lion_king.jpg",        discover: 6   ,    background: "images/backgrounds/lion_king_main_backg.jpg"},
    { title: "The Lorax",                        href: "../movies/the_lorax_movie.html",                   genre: "animation", poster: "images/posters/lr.jpg",               discover: 6 ,    background: "images/backgrounds/the_lorax_backg.jpg"},
    { title: "Despicable Me",                    href: "../movies/despicable_me_movie.html",               genre: "animation", poster: "images/posters/dm.jpg",               discover: 6 ,    background: "images/backgrounds/despicable_me_backg.jpg"},
    { title: "Mufasa: The Lion King",            href: "../movies/mufasa_movie.html",                      genre: "family",    poster: "images/posters/mf.jpg",               discover: 6 ,    background: "images/backgrounds/mufasa_backg.jpg"},
    { title: "Dune",                             href: "../movies/dune_movie.html",                        genre: "scifi",     poster: "images/posters/dn.jpg",               discover: 6 ,    background: "images/backgrounds/dune_backg.jpg"},
    { title: "Hunger Games",                     href: "../movies/hunger_games_movie.html",                genre: "action",    poster: "images/posters/hg.jpg",               discover: 6 ,    background: "images/backgrounds/hunger_games_backg.jpg"},
    { title: "Hercules",                         href: "../movies/hercules_movie.html",                    genre: "fantasy",   poster: "images/posters/he.jpg",               discover: 6   ,    background: "images/backgrounds/hercules_backg.jpg"},
    { title: "Sinners",                          href: "../movies/sinners_movie.html",                     genre: "thriller",  poster: "images/posters/si.jpg",               discover: 6 ,    background: "images/backgrounds/sinners_backg.jpg"},
    { title: "Ballerina",                        href: "../movies/ballerina_movie.html",                   genre: "action",    poster: "images/posters/bal.jpg",              discover: 7 ,    background: "images/backgrounds/ballerina_main_backg.jpg"},
    { title: "Black Panther: Wakanda Forever",     href: "../movies/black_panther_II_movie.html",            genre: "superhero", poster: "images/posters/black_panther.jpg",    discover: 7 ,    background: "images/backgrounds/black_panther_II_backg.jpg"},
    { title: "Wish",                             href: "../movies/wish_movie.html",                        genre: "animation", poster: "images/posters/wish.jpg",             discover: 7 ,    background: "images/backgrounds/wish_backg.jpg"},
    { title: "Descendants 3",                    href: "../movies/descendants_3_movie.html",               genre: "musical",   poster: "images/posters/descendants_3.jpg",      discover: 7 ,    background: "images/backgrounds/descendants_3_backg.jpg"},
    { title: "Aladdin",                          href: "../movies/aladdin_movie.html",                     genre: "animation", poster: "images/posters/alad.jpg",             discover: 7 ,    background: "images/backgrounds/aladdin_backg.jpg"},
    { title: "Kpop Demon Hunters",               href: "../movies/kpop_demon_hunters_movie.html",          genre: "animation", poster: "images/posters/kpop.jpg",             discover: 7 ,    background: "images/backgrounds/kpop_demon_hunters_backg.jpg"},
    { title: "Monster High",                     href: "../movies/monster_high_movie.html",                genre: "musical",   poster: "images/posters/mh.jpg",               discover: 7 ,    background: "images/backgrounds/monster_high_backg.jpg"},
    { title: "Tangled",                          href: "../movies/tangled_movie.html",                     genre: "animation", poster: "images/posters/tangled.jpg",          discover: 7 ,    background: "images/backgrounds/tangled_backg.jpg"},
    { title: "Avatar Aang: The Last Airbender", href: "../movies/avatar_aang_the_last_airbender_movie.html", genre: "fantasy", poster: "images/posters/avatar_aang_the_last_airbender.jpg", discover: 1 ,    background: "images/backgrounds/avatar_aang_the_last_airbender_backg.jpg"}
];
